services:
  emishows:
    build:
      context: ./
      network: host
    environment:
      - "EMISHOWS__SERVER__HOST=${EMISHOWS__SERVER__HOST:-0.0.0.0}"
      - "EMISHOWS__SERVER__PORT=${EMISHOWS__SERVER__PORT:-35000}"
      - "EMISHOWS__DATABASE__SQL__HOST=${EMISHOWS__DATABASE__SQL__HOST:-localhost}"
      - "EMISHOWS__DATABASE__SQL__PORT=${EMISHOWS__DATABASE__SQL__PORT:-34000}"
      - "EMISHOWS__DATABASE__SQL__PASSWORD=${EMISHOWS__DATABASE__SQL__PASSWORD:-password}"
      - "EMISHOWS__EMITIMES__CALDAV__SCHEME=${EMISHOWS__EMITIMES__CALDAV__SCHEME:-http}"
      - "EMISHOWS__EMITIMES__CALDAV__HOST=${EMISHOWS__EMITIMES__CALDAV__HOST:-localhost}"
      - "EMISHOWS__EMITIMES__CALDAV__PORT=${EMISHOWS__EMITIMES__CALDAV__PORT:-36000}"
      - "EMISHOWS__EMITIMES__CALDAV__PATH=${EMISHOWS__EMITIMES__CALDAV__PATH:-}"
      - "EMISHOWS__EMITIMES__CALDAV__USER=${EMISHOWS__EMITIMES__CALDAV__USER:-user}"
      - "EMISHOWS__EMITIMES__CALDAV__PASSWORD=${EMISHOWS__EMITIMES__CALDAV__PASSWORD:-password}"
      - "EMISHOWS__EMITIMES__CALDAV__CALENDAR=${EMISHOWS__EMITIMES__CALDAV__CALENDAR:-emitimes}"
    network_mode: host
